#

.base-docker-image-stage:
  image: docker:$DOCKER_VERSION
  services:
    - docker:$DOCKER_VERSION-dind

#

.base-docker-kube-image-stage:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
    - source ./.gitlab-ci/env.sh
    - /apps/create-kubeconfig.sh
    - if [ -n "${COMMIT_TAG}" || -n "${PRODUCTION+x}" ]; then SUFFIX=".prod"; else SUFFIX=".dev"; fi
